version: '3.8'

services:
  db:
    build:
      context: .
    image: postgres:13.14-bullseye
    container_name: db
    environment:
      POSTGRES_USER: 'bagas'
      POSTGRES_PASSWORD: 'bagas'
      POSTGRES_DB: 'computer_club'
    ports:
      - "5438:5438"
    volumes:
      - db-data:/var/lib/postgresql/data
    command:
      -p 5438
    restart: unless-stopped

  flyway:
    image: flyway/flyway:10.12.0-alpine
    container_name: flyway
    command:
      -url=jdbc:postgresql://db:5438/computer_club
      -user=bagas
      -password=bagas
      -schemas=public
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  db-data:
    external: false
  migration:
    external: false
  data-portainer:
    external: false

