CREATE SEQUENCE IF NOT EXISTS group_id_sequence START 101;

CREATE SEQUENCE IF NOT EXISTS category_id_sequence START 101;

CREATE SEQUENCE IF NOT EXISTS subcategory_id_sequence START 101;

CREATE SEQUENCE IF NOT EXISTS product_id_sequence START 101;

CREATE SEQUENCE IF NOT EXISTS description_id_sequence START 101;
